[versions]
# Fabric & Minecraft
minecraft = "1.21.10"
yarn = "1.21.10+build.2"
loader = "0.17.3"
fabricLoom = "1.11-SNAPSHOT"

[libraries]
# Fabric
minecraft-mojang = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabricLoom" }
